### ISSUE TITLE
GIFV Imgur links don't work

### ISSUE THREAD

**Issue by wardrich** [chirag64/Imgur-To-Filmot#2]
The plugin needs some logic to look for "gifv" links and strip the "v" off of the end.

ie:
http://imgur.com/picture.gifv -> http://filmot.org/picture.gif

**Comment by chirag64** [comment]
I tried a couple of links with gifv on filmot and they seem to be working fine for me. Can you post the link of an example image where you're able to reproduce this issue?

**Comment by wardrich** [comment]
Hey, sorry for not getting back to you sooner.  It might just be something related to my network settings.  If they're working fine for you (and nobody else seems to have said anything) I think it's safe to close this one off.
